version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@samjnvv4v08jp30q_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=BDY2201_S1
      - spring.datasource.password=ActForm.S1_BDY
    restart: always